name: 'Kustomize Build'
on:
  - workflow_dispatch
  - pull_request
jobs:
  kustomize:
    name: 'Kustomize'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Install kustomize'
        uses: ./.github/workflows/install-kustomize/
        with:
          kustomize-version: 5.0.1
      - run: kustomize version
      - run: ./scripts/test-kustomize-build.sh .

